tasks:
  task1:
    scheduler:
      day: MONDAY
      hour: '20:00'
    description: "Dizer 'Olá mundo'"
    commands:
      - 'say Hello World :)'
  task2:
    scheduler:
      day: MONDAY
      hour: '20:00'
    description: "Distribuir caixas."
    commands:
      - 'caixa all'
      - 'say Foi dado uma caixa para todos os jogadores online!'
